[package]
name = "kserver"
version = "0.1.0"
authors = ["Alexander Lindermayr <linderal@uni-bremen.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mcmf = "2.0.0"
structopt = "0.2.10"
rand = "0.7.3"
indicatif = "0.14.0"
console = "0.9.2"
